In [1]:
import numpy as np

In [6]:
#List va Array
my_list = list(range(10000)) # python list --> Normal
my_array = np.array(range(10000)) #numpy array - Vektor

In [9]:
%timeit for _ in range(10):[x*2 for x in my_list] #Normal

10.6 ms ± 805 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [11]:
%timeit for _ in range(10):[x*2 for x in my_array] #Vektor

27 ms ± 7.17 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [4]:
# numpy arrayga ogirish
data1 = [1,2,3,4,5]
arr1 = np.array(data1)

In [5]:
arr1

array([1, 2, 3, 4, 5])

In [7]:
arr1.ndim # array size

1

In [10]:
data2 = [
[1, 2, 3, 4],
[5, 6, 7, 8]
]

arr2 = np.array(data2)
arr2.ndim

2

In [11]:
arr2.shape # qator va ustun

(2, 4)

In [12]:
arr2.size # elementlar soni

8

In [13]:
arr4 = np.zeros(shape=(3,4)) # barcha elementlarni 0 lar bilan toldiradi
arr4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
arr5 = np.ones(shape=(3,4)) # barcha elementlarni 1 lar bilan to'ldiradi
arr5

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
arr6 = np.arange(start=1, stop=20, step=2) # 1 dan 20gacha bolgan sonlarni 2 qadam tashlab sanab chiqadi 20 kirmaydi
arr6

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [25]:
arr7 = np.array([1,2,3], dtype=np.int64)
arr7.dtype

dtype('int64')

In [2]:
float_arr = arr7.astype(np.float64)
float_arr.dtype

NameError: name 'arr7' is not defined

In [3]:

# np.arange() - ma’lum oraliqdagi massiv yaratish
arr = np.arange(1, 11, 2)  # 1 dan 10 gacha, qadam 2
print(arr)


NameError: name 'zero_arr' is not defined

In [4]:
# 0 lar bilan to‘ldirilgan massiv
zero_arr = np.zeros((3, 3))
zero_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# 1 lar bilan to‘ldirilgan massiv
ones_arr = np.ones((2, 4))
ones_arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
# Tasodifiy sonlardan iborat massiv
rand_arr = np.random.rand(3, 3)
rand_arr

array([[0.21289331, 0.61369492, 0.5512861 ],
       [0.84841314, 0.27133745, 0.58975847],
       [0.54604959, 0.80117012, 0.82187319]])

In [8]:
arr = np.arange(1, 11, 2)  # 1 dan 10 gacha, qadam 2
arr

array([1, 3, 5, 7, 9])

In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
# Massiv o‘lchami (shape)
arr.shape

(2, 3)

In [12]:
# Massivni qayta shakllantirish (reshape)
reshaped_arr = arr.reshape(3, 2)
reshaped_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
# Massivni tekis (1D) ko‘rinishga keltirish (flatten)
flattened_arr = arr.flatten() 
flattened_arr

array([1, 2, 3, 4, 5, 6])

In [16]:
arr = np.array([10, 20, 30, 40, 50])


In [18]:
# Bitta elementni olish
arr[2] # 30


np.int64(30)

In [20]:
# Dilim (slicing) – 2-chi indeksdan boshlab 4-gacha (4 kirmaydi)
arr[2:4]  # [30 40]

array([30, 40])

In [22]:
arr[::2] # [10 30 50]

array([10, 30, 50])

In [24]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [25]:
# Qo‘shish
a + b  # [5 7 9]

array([5, 7, 9])

In [26]:
# Ayirish
a - b  # [-3 -3 -3]


array([-3, -3, -3])

In [27]:
# Ko‘paytirish
a * b # [4 10 18]

array([ 4, 10, 18])

In [28]:
# Bo‘lish
a / b # [0.25 0.4  0.5 ]

array([0.25, 0.4 , 0.5 ])